default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: one-bit-exchange_development


test:
  <<: *default
  database: one-bit-exchange_test
 

production:
  <<: *default
  database: one-bit-exchange_production
  username: one-bit-exchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>